### DISCUSSION TITLE
https://theme-hope.vuejs.press/zh/guide/customize/

### DISCUSSION THREAD

**Discussion by giscus** [vuepress-theme-hope/giscus-discussions#800] [Announcements]
# https://theme-hope.vuejs.press/zh/guide/customize/

此章节向你演示常见的自定义需求涉及的相关代码。

https://theme-hope.vuejs.press/zh/guide/customize/

**Comment by wzh656** [comment]
请问怎么设置主页的背景图啊，我现在只能通过`index.scss`里
```scss
.vp-blog-mask{
	background-image: url(./assets/images/background.jpg) !important;
}
```
来强制设置，请问有没有在主题中配置的属性？（我没有找到有关的文档）
